FROM ubuntu:22.04

# Install necessary dependencies
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update \
    && apt-get install -y wget bzip2 make unzip cppcheck gcc-arm-none-eabi


# Create a non-root user named "ubuntu"
# But put it n root-group since Github needs permission to create tmp files.
RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo \
    -u 1001 ubuntu
USER ubuntu
WORKDIR /home/ubuntu